apiVersion: apps/v1
kind: Deployment
metadata:
 name: nginx-deploy
 labels:
  app: webserver
spec:
 selector:
  matchLabels:
    app: webserver
 replicas: 2
 template:
   metadata:
    name: nginx
    labels:
     app: webserver
   spec:
    containers:
     - name: nginx
       image: nginx:latest
       ports:
         - containerPort: 90
